### ISSUE TITLE
killed and exit R

### ISSUE THREAD

**Issue by wzhang42** [ThomasBeder/ALLCatchR#8]
Hi, Thanks for your developping ALLCatchR, but when I play with it, it always report messages "Killed" and exit
even I played with your default data such as 
....
allcatch(Counts.file = NA, ID_class = "symbol", sep = "\t")
test counts loaded...
0  of  15745  genes not found
ML prediction...
Classification using ssGSEA...
Killed
...

**Comment by jotech** [comment]
Hi @wzhang42 
Thank you for using ALLCatchR!
This sounds like R is killed by the OS because you are missing resources. Are you working on a computer cluster and if yes could you specify what resources (memory) you allocated for the job?

**Comment by wzhang42** [comment]
Yes, I work in our HPC cluster. I also agree that R is killed by OS.  I just test it in a login node, so the memory is not limited in principle.  Additionally, cmd allcatch(Counts.file = NA, ID_class = "symbol", sep = "\t") is very simple, and it seems only play with the demo count matrix. So, I do not think this is memory issue.

**Comment by jotech** [comment]
Thanks for the clarification!

Just to be sure, did the error also appear when you call 
```
library(ALLCatchR)
allcatch()
```
?

Since it seems to be OS-related, it is hard to help here without any log files. Maybe you can have a look at something like [(1)](https://stackoverflow.com/questions/3426356/what-causes-an-r-script-to-get-killed) and/or get in contact with the admins from your cluster?
